//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorcEkle
    {
        public int BorcID { get; set; }
        public string BorcAciklama { get; set; }
        public string BorcHesapAdi { get; set; }
        public decimal BorcTutar { get; set; }
        public System.DateTime BorcDuzenlenmeTarihi { get; set; }
        public System.DateTime BorcSonOdemeTarihi { get; set; }
        public string BorcKategori { get; set; }
        public Nullable<bool> BorcOdemeDurumu { get; set; }
        public decimal BorcToplam { get; set; }
        public decimal BorcKalan { get; set; }
    }
}
